name: Publish Package

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch (adjust as needed)
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          source $HOME/.bashrc  # Ensure that the shell session is updated with Bun's path

      # Step 3: Verify Bun installation
      - name: Verify Bun installation
        run: |
          bun --version  # Check if Bun is successfully installed

      # Step 4: Install dependencies using Bun
      - name: Install dependencies
        run: bun install  # Install dependencies using Bun

      # Step 5: Run TypeScript build if needed (optional)
      - name: Build TypeScript
        run: bun run tsc  # Run TypeScript compiler if needed


      - name: Check Environment Variables
        run: printenv

      # Step 6: Publish package to npm
      - name: Publish package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure that the token is being passed properly
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public  # Or private, depending on your settings
