name: Publish Package

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch (adjust as needed)
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Bun manually
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash  # Install Bun
          echo "$HOME/.bun/bin" >> $GITHUB_PATH       # Add Bun to the PATH

      # Step 3: Verify Bun installation
      - name: Verify Bun installation
        run: |
          bun --version  # This will check if Bun is successfully installed

      # Step 4: Install dependencies using Bun
      - name: Install dependencies
        run: bun install  # Using Bun to install dependencies

      # Step 5: Run TypeScript build if needed (optional)
      - name: Build TypeScript
        run: bun run ./index.ts  # Run TypeScript compiler if needed

      # Step 6: Publish package to npm
      - name: Publish package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken'="${NPM_TOKEN}"
          npm publish --access public  # Or private, depending on your settings
